services:
  bot:
    build: .
    depends_on:
      - lavalink
    restart: unless-stopped
    env_file: .env
    environment:
      # - DBURL=postgresql://fridaylocal:fridaylocal@db:5432/fridaylocal
      - LAVALINKUSHOST=lavalink
      - LAVALINKUSPORT=2333
      - LAVALINKUSPASS=lavalink
      - WAIT_HOSTS=db:5432
    volumes:
      - .:/usr/src/app
      - /home/certs/:/home/certs/
    ports:
      - 5678:5678
      - 443:443
    # entrypoint: sh -c "/wait && python3 index.py db upgrade && exec python3 index.py"
    # entrypoint: sh -c "exec python3 index.py"
  lavalink:
    image: fredboat/lavalink:dev
    restart: unless-stopped
    ports:
      - 2333:2333
    volumes:
      - ./lavalink.config.yml:/opt/Lavalink/application.yml
  db:
    image: postgres:15.1
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    logging:
      driver: "none"
    volumes:
      - pgadmin:/var/lib/pgadmin
  # portainer:
  #   image: portainer/portainer-ce
  #   restart: always
  #   ports:
  #     - 8000:8000
  #     - 9000:9000
  #     - 9443:9443
  #   depends_on:
  #     - bot
  #   logging:
  #     driver: "none"
  #   volumes:
  #     - portainer:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     # - pgadmin:/var/run/docker.sock

volumes:
  db:
  pgadmin:
  # portainer: