services:
  bot:
    build: .
    depends_on:
      - lavalink
    restart: unless-stopped
    env_file: .env
    environment:
      # - DBURL=postgresql://fridaylocal:fridaylocal@db:5432/fridaylocal
      - LAVALINKDOCKERHOST=lavalink
      - LAVALINKDOCKERPORT=2333
      - LAVALINKDOCKERPASS=lavalink
      # - WAIT_HOSTS=db:5432
    volumes:
      - .:/usr/src/app
    ports:
      - 5678:5678
    # entrypoint: sh -c "/wait && cp -r /opt/venv . && pip -V && exec python3 index.py"
    entrypoint: sh -c "exec python3 index.py"
  lavalink:
    image: fredboat/lavalink
    restart: unless-stopped
    ports:
      - 2333:2333
    volumes:
      - ./lavalink.config.yml:/opt/Lavalink/application.yml
  # db:
  #   image: postgres:15.1
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=fridaylocal
  #     - POSTGRES_PASSWORD=fridaylocal
  #     - POSTGRES_DB=fridaylocal
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #     - ./migrations:/docker-entrypoint-initdb.d
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80
  #   logging:
  #     driver: "none"
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin
volumes:
  db:
#     driver: "local"
  # pgadmin: