name: Will it blend?

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Launch check os ${{ matrix.os }}, Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.I18N_SUBMODULE_GH_ACTIONS_PULL }}
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt
    - name: Install google key for translations
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}
      run: |
        if ! [ -f friday-trans-key.json ]; then python create_trans_key.py; fi
        if [ -f friday-trans-key.json ]; then printf "File created"; fi
    - name: Test with pytest
      env:
        DBHOSTNAME: ${{ secrets.DBHOSTNAME }}
        DBUSERNAME: ${{ secrets.DBUSERNAME }}
        DBUSERNAMECANARY: ${{ secrets.DBUSERNAMECANARY }}
        DBUSERNAMELOCAL: ${{ secrets.DBUSERNAMELOCAL }}
        DBPASSWORD: ${{ secrets.DBPASSWORD }}
        DBPASSWORDCANARY: ${{ secrets.DBPASSWORDCANARY }}
        DBPASSWORDLOCAL: ${{ secrets.DBPASSWORDLOCAL }}
        DBDATABASE: ${{ secrets.DBDATABASE }}
        DBDATABASECANARY: ${{ secrets.DBDATABASECANARY }}
        DBDATABASELOCAL: ${{ secrets.DBDATABASELOCAL }}
        TOKENTEST: ${{ secrets.TOKENTEST }}
        DBLWEBHOOKPASS: ${{ secrets.DBLWEBHOOKPASS }}
        WEBHOOKSPAMID: ${{ secrets.WEBHOOKSPAMID }}
        WEBHOOKISSUESID: ${{ secrets.WEBHOOKISSUESID }}
        WEBHOOKINFOID: ${{ secrets.WEBHOOKINFOID }}
        WEBHOOKERRORSID: ${{ secrets.WEBHOOKERRORSID }}
        WEBHOOKCHATID: ${{ secrets.WEBHOOKCHATID }}
        WEBHOOKJOINID: ${{ secrets.WEBHOOKJOINID }}
        WEBHOOKSPAMTOKEN: ${{ secrets.WEBHOOKSPAMTOKEN }}
        WEBHOOKISSUESTOKEN: ${{ secrets.WEBHOOKISSUESTOKEN }}
        WEBHOOKINFOTOKEN: ${{ secrets.WEBHOOKINFOTOKEN }}
        WEBHOOKERRORSTOKEN: ${{ secrets.WEBHOOKERRORSTOKEN }}
        WEBHOOKCHATTOKEN: ${{ secrets.WEBHOOKCHATTOKEN }}
        WEBHOOKJOINTOKEN: ${{ secrets.WEBHOOKJOINTOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        REDDITCLIENTID: ${{ secrets.REDDITCLIENTID }}
        REDDITCLIENTSECRET: ${{ secrets.REDDITCLIENTSECRET }}
        REDDITPASSWORD: ${{ secrets.REDDITPASSWORD }}
        APIREQUESTS: ${{ secrets.APIREQUESTS }}
      run: |
        if [ -f friday-trans-key.json ]; then printf "Google file here"; fi
        pytest test_will_it_blend.py