name: ci
on:
  push:
    branches:
      - master
      - canary
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then python -m pip install -r docs/requirements.txt; fi
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - run: python build_docs.py
        env:
          TOKENTEST: ${{ secrets.TOKENTEST }}
          DATABASE: ${{ secrets.DATABASE }}
          DATABASETEST: ${{ secrets.DATABASETEST }}
          DBLWEBHOOKPASS: ${{ secrets.DBLWEBHOOKPASS }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASS: ${{ secrets.DBPASS }}
          DBHOST: ${{ secrets.DBHOST }}
          WEBHOOKSPAM: ${{ secrets.WEBHOOKSPAM }}
          WEBHOOKISSUES: ${{ secrets.WEBHOOKISSUES }}
          WEBHOOKINFO: ${{ secrets.WEBHOOKINFO }}
          WEBHOOKERRORS: ${{ secrets.WEBHOOKERRORS }}
          WEBHOOKCHAT: ${{ secrets.WEBHOOKCHAT }}
          WEBHOOKJOIN: ${{ secrets.WEBHOOKJOIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: mkdocs gh-deploy